<?php
$data = '{"ACTIVITY":{"1":{"ACTIVITYID":1,"ACTIVITY_DESC":"Dashboard","ACTIVITY_PAGE":"DASHBOARD","ACTROLE_STATUS":null,"IS_MENU":"Y","SUBACTIVITY":""},"2":{"ACTIVITYID":2,"ACTIVITY_DESC":"Master","ACTIVITY_PAGE":"MASTER","ACTROLE_STATUS":null,"IS_MENU":"Y","SUBACTIVITY":{"3":{"ACTIVITYID":3,"ACTIVITY_DESC":"Category::Category Listing","ACTIVITY_PAGE":"CATEGORY","PARENT_ACTIVITYID":2,"PARENT_ACTIVITY":"Master","ACTROLE_STATUS":"Y","IS_MENU":"Y","SUBACTIVITY":{"5":{"ACTIVITYID":5,"ACTIVITY_DESC":"Category::Add Category","ACTIVITY_PAGE":"ADD_CATEGORY","PARENT_ACTIVITYID":3,"PARENT_ACTIVITY":"Category:Category Listing","ACTROLE_STATUS":"Y","IS_MENU":"N","SUBACTIVITY":""},"6":{"ACTIVITYID":6,"ACTIVITY_DESC":"Category::Edit Category","ACTIVITY_PAGE":"EDIT_CATEGORY","PARENT_ACTIVITYID":3,"PARENT_ACTIVITY":"Category:Category Listing","ACTROLE_STATUS":"Y","IS_MENU":"N","SUBACTIVITY":""},"10":{"ACTIVITYID":10,"ACTIVITY_DESC":"Country :: Country Listing","ACTIVITY_PAGE":"LIST_COUNTRY","PARENT_ACTIVITYID":3,"PARENT_ACTIVITY":"Category:Category Listing","ACTROLE_STATUS":"Y","IS_MENU":"Y","SUBACTIVITY":{"11":{"ACTIVITYID":11,"ACTIVITY_DESC":"Country::Add Country","ACTIVITY_PAGE":"ADD_COUNTRY","PARENT_ACTIVITYID":10,"PARENT_ACTIVITY":"Country :: Country Listing","ACTROLE_STATUS":"Y","IS_MENU":"N","SUBACTIVITY":""},"12":{"ACTIVITYID":12,"ACTIVITY_DESC":"Country::Edit Country","ACTIVITY_PAGE":"EDIT_COUNTRY","PARENT_ACTIVITYID":10,"PARENT_ACTIVITY":"Country :: Country Listing","ACTROLE_STATUS":"Y","IS_MENU":"N","SUBACTIVITY":""}}}}}}},"4":{"ACTIVITYID":4,"ACTIVITY_DESC":"Product","ACTIVITY_PAGE":"PRODUCT","ACTROLE_STATUS":null,"IS_MENU":"Y","SUBACTIVITY":""},"7":{"ACTIVITYID":7,"ACTIVITY_DESC":"CITY :: City Listing","ACTIVITY_PAGE":"LIST_CITY","ACTROLE_STATUS":"Y","IS_MENU":"Y","SUBACTIVITY":{"8":{"ACTIVITYID":8,"ACTIVITY_DESC":"City::Add City","ACTIVITY_PAGE":"ADD_CITY","PARENT_ACTIVITYID":7,"PARENT_ACTIVITY":"CITY :: City Listing","ACTROLE_STATUS":"Y","IS_MENU":"N","SUBACTIVITY":""},"9":{"ACTIVITYID":9,"ACTIVITY_DESC":"City::Edit City","ACTIVITY_PAGE":"EDIT_CITY","PARENT_ACTIVITYID":7,"PARENT_ACTIVITY":"CITY :: City Listing","ACTROLE_STATUS":"Y","IS_MENU":"N","SUBACTIVITY":""}}}}}';


$activity = json_decode($data,true);
print'<pre>';print_r($activity['ACTIVITY']);
 $activity_arr = array();
foreach($activity['ACTIVITY'] as $key=>$value){

	if($value['IS_MENU'] == 'Y'){
		$activity_arr[$key] = $value;
	}

	if(isset($value['SUBACTIVITY']) && !empty($value['SUBACTIVITY'])){

	)


} 